#include "jinx.h"

#include "x11.c"
#include "eventHandler.c"

#include "core/jid.c"
#include "core/renderer.c"
#include "core/helpers.c"
#include "core/renderFunctions.c"
#include "core/layouts.c"
#include "core/events.c"
#include "jinxst/reader.c"
#include "jinxst/jinxst.c"
// #include "jinxst/log.c"
#include "jinxst/tokenizer.c"
#include "jinxst/jinxstTable.c"
// #include "core/tooltip.c"
